### ISSUE TITLE
Assignment 8 Completed

### ISSUE THREAD

**Issue by DanielSegarra36** [hunter-college-cs-ossd/DanieSegarra36-git-exercise-02#5]
All conflicts resolved and teammate entries have been merged to master.

**Comment by stewartweiss** [comment]
@DanieSegarra36 
The program does not compile:
`main.cpp:64:30: error: ‘DanieSegarra36_oddity’ was not declared in this scope
     output_function intro = &DanieSegarra36_oddity;
`
This is easily fixed but you need to do that.

**Comment by stewartweiss** [comment]
@DanieSegarra36 
I did not mean to close this issue. Please fix and notify me after.

**Comment by DanielSegarra36** [comment]
> @DanieSegarra36
> The program does not compile:
> `main.cpp:64:30: error: ‘DanieSegarra36_oddity’ was not declared in this scope output_function intro = &DanieSegarra36_oddity; `
> This is easily fixed but you need to do that.

@stewartweiss 
Fixed this issue and pushed the changes.

**Comment by stewartweiss** [comment]
@DanieSegarra36 
Yes it is fixed. Good job.
